# Generated by Django 4.1.4 on 2023-11-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_doc',
            field=models.BooleanField(default=False),
        ),
    ]
