# Generated by Django 4.1.4 on 2024-03-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_is_doc_profile_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doc_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
