# Generated by Django 4.1.4 on 2024-03-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appointment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_model',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
